Removing binary dependency
criblio/node-unzipper pull request #2
Opened 2023-08-08 05:49 UTC by amcgoogan

Removing dependency on the 'binary' package and using node's built-in buffer module to perform unsigned LE number parsing.

testing:
npm install
npm test

2023-08-10 14:20 UTC, pdugas requested changes
Checked the byte lengths of the translated `parse()` calls and don't see any diffs.  

Had one nit you can ignore if you like. 

Think we need to add a UT for the new `parseBuffer()` function.

2023-08-10 14:20 UTC, pdugas commented on lib/parseBuffer.js
> +      result[key] = parseUIntLE(buffer, offset, size);
Should this be `bufer.parseUIntLE()` so it's consistent with they way it's used above?

2023-08-10 14:20 UTC, pdugas commented on lib/parseBuffer.js
> +const parse = function(buffer, format) {
Should we UT this function?

2023-08-10 21:38 UTC, amcgoogan commented on lib/parseBuffer.js
> +const parse = function(buffer, format) {
Added test.

2023-08-10 21:55 UTC, pdugas commented on lib/parseBuffer.js
> +      result[key] = parseUIntLE(buffer, offset, size);
duh, being an idiot...

2023-08-14 15:01 UTC, pdugas approved these changes

2023-08-14 18:45 UTC, zach-cribl approved these changes
Removes old package with problematic license and maintains needed functionality 👍

2023-08-14 19:17 UTC, nromito approved these changes

2023-08-14 20:08 UTC, merged